version: '3.3'

services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '2181:2181'
    networks:
       kafka:
        aliases:
          - kafka
  
          
  kafka-1:  
      image: wurstmeister/kafka:latest
      deploy: 
            mode: global

      restart: always
      
      ports:
       - "9093:9093"
       - "19092:19092"

      environment: 
         KAFKA_BROKER_ID: 1
         HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
         #HOSTNAME_COMMAND: curl http://169.254.169.254/hetzner/v1/metadata/hostname
         KAFKA_ADVERTISED_LISTENERS: INSIDE://_{HOSTNAME_COMMAND}:19092,OUTSIDE://168.119.119.105:9093
         #KAFKA_ADVERTISED_LISTENERS: INSIDE://:19092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
         KAFKA_LISTENERS: INSIDE://:19092,OUTSIDE://:9093
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
         KAFKA_CREATE_TOPICS: myTopic:1:1
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
       kafka:
        aliases:
          - kafka-1

  kafka-2:  
      image: wurstmeister/kafka:latest
      deploy: 
            mode: global

      restart: always
      
      ports:
       - "9094:9094"
       - "29092:29092"

      environment: 
         KAFKA_BROKER_ID: 2
         HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
         #HOSTNAME_COMMAND: curl http://169.254.169.254/hetzner/v1/metadata/hostname
         KAFKA_ADVERTISED_LISTENERS: INSIDE://_{HOSTNAME_COMMAND}:29092,OUTSIDE://116.203.112.49:9094
         #KAFKA_ADVERTISED_LISTENERS: INSIDE://:19092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
         KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9094
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
         KAFKA_CREATE_TOPICS: myTopic:1:1
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
       kafka:
        aliases:
          - kafka-2

  kafka-3:  
      image: wurstmeister/kafka:latest
      deploy: 
            mode: global

      restart: always
      
      ports:
       - "9095:9095"
       - "39092:39092"

      environment:
         KAFKA_BROKER_ID: 3
         HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
         #HOSTNAME_COMMAND: curl http://169.254.169.254/hetzner/v1/metadata/hostname
         KAFKA_ADVERTISED_LISTENERS: INSIDE://_{HOSTNAME_COMMAND}:39092,OUTSIDE://94.130.79.164:9095
         #KAFKA_ADVERTISED_LISTENERS: INSIDE://:19092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
         KAFKA_LISTENERS: INSIDE://:39092,OUTSIDE://:9095
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
         KAFKA_CREATE_TOPICS: myTopic:1:1
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
       kafka:
        aliases:
          - kafka-3

networks:
  kafka:
    external: true